---
- name: If choosing custom package set, ensure minimal cockpit is included
  set_fact:
    cockpit_packages: "{{ cockpit_packages + __cockpit_packages_minimal
                          if cockpit_packages not in __cockpit_package_types
                          else cockpit_packages }}"
  when: cockpit_packages is defined

- name: Determine all Cockpit Web Console packages
  when: cockpit_packages == "full"
  changed_when: false
  shell: |
    set -euo pipefail
    dnf repoquery --latest-limit=1 --queryformat '%{name}\n' | grep -E '^cockpit-'
  register: __cockpit_packages_full

- name: Ensure Cockpit Web Console packages are installed
  dnf:
    name: "{{ (__cockpit_packages_minimal +
              __cockpit_packages_full.stdout_lines | difference(__cockpit_packages_exclude))
              if cockpit_packages == 'full'
              else
                  __cockpit_packages[cockpit_packages]
                  if cockpit_packages in __cockpit_package_types
                  else cockpit_packages }}"
    # FIXME: this does not belong here, as it filters out explicit user-specified package lists as well
    exclude: "{{ __cockpit_packages_exclude }}"
    state: present
