---
# Variable configuration.
- name: Include OS-specific variables (RedHat & Fedora).
  include_vars: "{{ ansible_distribution }}-{{ ansible_distribution_version.split('.')[0] }}.yml"
  when: ansible_os_family == 'RedHat'

- name: Include OS-specific variables (Debian).
  include_vars: "{{ ansible_distribution }}-{{ ansible_distribution_version.split('.')[0] }}.yml"
  when: ansible_os_family == 'Debian'

- name: Define cockpit_daemon.
  set_fact:
    cockpit_daemon: "{{ __cockpit_daemon }}"
  when: cockpit_daemon is not defined

- name: Define cockpit_packages.
  set_fact:
    cockpit_packages: "{{ __cockpit_packages | list }}"
  when: cockpit_packages is not defined

# ansible fedora -c local -m setup | grep -ie ansible_os -e distribution
#         "ansible_distribution": "Fedora",
#         "ansible_distribution_file_parsed": true,
#         "ansible_distribution_file_path": "/etc/redhat-release",
#         "ansible_distribution_file_variety": "RedHat",
#         "ansible_distribution_major_version": "30",
#         "ansible_distribution_release": "",
#         "ansible_distribution_version": "30",
#         "ansible_os_family": "RedHat",
# ansible localhost -c local -m setup | grep -ie ansible_os -e distribution
#         "ansible_distribution": "RedHat",
#         "ansible_distribution_file_parsed": true,
#         "ansible_distribution_file_path": "/etc/redhat-release",
#         "ansible_distribution_file_search_string": "Red Hat",
#         "ansible_distribution_file_variety": "RedHat",
#         "ansible_distribution_major_version": "8",
#         "ansible_distribution_release": "Ootpa",
#         "ansible_distribution_version": "8.0",
#         "ansible_os_family": "RedHat",
