---
# handlers file for cockpit
- name: reload systemd
  systemd:
    daemon_reload: true

- name: restart cockpit
  service:
    name: "{{ __cockpit_daemon }}"
    state: "{{ 'restarted' if cockpit_started | bool else 'stopped' }}"
