---
# handlers file for cockpit
- name: Reload systemd
  systemd:
    daemon_reload: true

- name: Restart cockpit
  service:
    name: "{{ __cockpit_daemon }}"
    # noqa args[module]
    state: "{{ 'restarted' if cockpit_started | bool else 'stopped' }}"
