---
__cockpit_daemon: cockpit.socket

__cockpit_packages_minimal:
  - cockpit-system
  - cockpit-ws

__cockpit_packages_default:
  - cockpit
  - cockpit-networkmanager
  - cockpit-packagekit
  - cockpit-selinux
  - cockpit-storaged

__cockpit_packages_full:
  - cockpit-*

__cockpit_packages:
  minimal: "{{ __cockpit_packages_minimal }}"
  default: "{{ __cockpit_packages_minimal + __cockpit_packages_default }}"
  full: "{{ __cockpit_packages_minimal + __cockpit_packages_default +
    __cockpit_packages_full }}"

__cockpit_packages_exclude:
  - cockpit-docker   # omit in favor of podman
  - cockpit-ostree   # omit only needed for rpm-ostree or CoreOS
  - cockpit-tests    # omit only needed for testing
