name: Integration

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - main
env:
  TOX_LSR: "git+https://github.com/richm/tox-lsr@container-improvements"
  LSR_CONFIG: "https://raw.githubusercontent.com/linux-system-roles/linux-system-roles.github.io/master/download/linux-system-roles.json"
  PARALLEL: "999"
  COLLECTION_SRC_OWNER: "linux-system-roles"
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        os: ["centos-7", "centos-8", "centos-9", "fedora-35", "fedora-36"]
        ansible_ver: ["ansible-2.9", "ansible-core-2.13"]
        collection: ["role", "collection"]

    steps:
      - uses: actions/checkout@v2

      - name: Install platform dependencies, python, tox, tox-lsr
        run: |
          set -euxo pipefail
          python -m pip install --upgrade pip
          sudo apt-get update
          sudo apt-get install -y git
          pip install "$TOX_LSR"

      - name: Run tests
        run: |
          if [ ! -d "$HOME/.config" ]; then
            mkdir -p "$HOME/.config"
          fi
          curl -o "$HOME/.config/linux-system-roles.json" "$LSR_CONFIG"
          toxenv="container-${{ matrix.ansible_ver }}"
          test_dir=tests
          if [ "${{ matrix.collection }}" = collection ]; then
            tox -e collection
            mv .tox/ansible_collections/fedora/linux_system_roles/tests .tox
            for file in .tox/tests/*/tests_default.yml; do
              test_dir="$(dirname "$file")"
              break
            done
          fi
          tox -e "$toxenv" -- --image-name "${{ matrix.os }}" \
            --parallel "$PARALLEL" "$test_dir"/tests_*.yml

      - name: Upload test logs
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: ${{ matrix.os }}_${{ matrix.ansible_ver }}_${{ matrix.collection }}_logs
          path: logs.tar.gz
