name: Integration tests
on:  # yamllint disable-line rule:truthy
  pull_request:
  # run them regularly, to catch changes in operating systems
  schedule:
    - cron: 0 4 * * MON

jobs:
  ubuntu:
    strategy:
      matrix:
        release:
          - ubuntu-20.04
          - ubuntu-22.04
    runs-on: '${{ matrix.release }}'
    timeout-minutes: 30
    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Install Ansible
        run: |
          sudo apt update
          sudo apt install -y ansible

      - name: Run test playbook
        run: |
          cd tests
          sudo ansible-playbook -vv --connection=local --inventory localhost, tests_*.yml
